/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mongodb.interfazgraficadeusuariosimple;

/**
 *
 * @author Alumno
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JButton();
        InputText2 = new javax.swing.JTextField();
        InputText1 = new javax.swing.JTextField();
        Boton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        Text1.setText("ESCRIBE TU NOMBRE");

        Text2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        Text2.setText("Nombre escrito del revés");

        Boton1.setText("REVERTIR");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        InputText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputText2ActionPerformed(evt);
            }
        });

        InputText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputText1ActionPerformed(evt);
            }
        });

        Boton2.setText("LIMPIAR");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                        .addComponent(InputText1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(InputText2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)))
                            .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))))
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(Boton1))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Boton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputText1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Boton1)
                .addGap(28, 28, 28)
                .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputText2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton2)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // Crea las variables a usar.
        String nombre, nombreInvertido;
        
        // Declara la variable "nombre" asignándole que su valor será el que el usuario ponga en "InputText1".
        nombre = InputText1.getText().trim(); /* El atributo ".trim" elimina espacios vacíos/en blanco tanto al principio como al final de la cadena*/
        
        // Declara la variable "nombreInvertido" asignándole que su valor será el valor recibido/almacenado en la variable "nombre". Todo esto dentro de un objeto, "StringBuilder".
        nombreInvertido = new StringBuilder(nombre).reverse().toString();/*
                                                                            * El atributo "reverse" se encarga de revertir la cadena, la escribe del revés.
                                                                            * El atributo "toString" vuelve a convertir el objeto obtenido en ".reverse" como una cadena de texto.
                                                                            */
                
        // Muestra el texto invertido en "InputText2".
        InputText2.setText(nombreInvertido);
    }//GEN-LAST:event_Boton1ActionPerformed

    private void InputText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputText2ActionPerformed

    private void InputText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputText1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // Inicializa o deja los bloques vacíos/en blanco
        InputText1.setText("");
        InputText2.setText("");
    }//GEN-LAST:event_Boton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JTextField InputText1;
    private javax.swing.JTextField InputText2;
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    // End of variables declaration//GEN-END:variables
}
